site_name: "Nevermined CLI Documentation"
site_description: "Nevermined, The world's first enterprise-grade unstoppable data sharing ecosystem"
site_author: Nevermined
site_url: http://docs.nevermined.io/

# Repository
repo_name: nevermined-io/cli
repo_url: https://github.com/nevermined-io/cli

# Copyright
copyright: "Copyright &copy; 2021 Nevermined"

theme:
  name: material
  language: en
  features:
    - navigation.expand
    # - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: default
    primary: black
    accent: indigo

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

  favicon: assets/nevermined/favicon-nvm.ico
  logo: assets/nevermined/favicon-32.png
  icon:
    repo: fontawesome/brands/git-alt

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: textileio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_captions


# Customization
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://nevermined.io
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/nevermined
    - icon: fontawesome/brands/medium
      link: https://medium.com/nevermined-io
    - icon: fontawesome/brands/github
      link: https://github.com/nevermined-io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nevermined_io
    - icon: fontawesome/brands/discord
      link: https://discord.gg/GZju2qScKq
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCaDKPgnEk4ekvQo2vO6FIBQ
    - icon: fontawesome/regular/paper-plane
      link: mailto:info@nevermined.io


#nav:
#  - Home: index.md
#  - Accounts: accounts.html
#  - Assets: assets.html
#  - Accounts MD: Accounts.md
#  - Social:
#    - Discord: https://discord.gg/GZju2qScKq
#    - Twitter: https://twitter.com/nevermined_io
#    - Linkedin: https://linkedin.com/company/nevermined
#    - Demos: https://www.youtube.com/channel/UCaDKPgnEk4ekvQo2vO6FIBQ

google_analytics:
  - G-H5FH0N6N2E
  - auto
