name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install minikube v1.12.0
        run: |
          wget https://storage.googleapis.com/minikube/releases/v1.12.0/minikube-linux-amd64
          chmod +x minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube

      - name: Reclaim some disk space
        run: |
          docker system prune --all --volumes -f

      - name: Start Nevermined
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          git clone https://github.com/keyko-io/nevermined-tools
          cd nevermined-tools
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"
          # start nevermined with the compute stack
          ./start_nevermined.sh --latest --no-commons --local-spree-node --compute &
          # wait for the compute api to be online.
          # the compute api is the last service to come online
          ./scripts/wait_for_compute_api.sh
          cd ..

      - name: Run tests
        run: |
          bash src/main/bash/updateConfAddresses.sh src/test/resources/networks/spree.conf
          bash src/main/bash/updateConfAddresses.sh src/main/resources/networks/spree.conf
          mvn clean verify -P integration-test
