name: documentation
on:
  push:
    branches:
      - master
      - main
jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install packages
        run: |
          sudo apt-get install -y asciidoctor
          sudo wget https://github.com/jgm/pandoc/releases/download/2.11.3.2/pandoc-2.11.3.2-1-amd64.deb
          sudo dpkg -i pandoc-2.11.3.2-1-amd64.deb
          pip install mkdocs-material markdown-captions mkdocs-markdownextradata-plugin
      - name: Generates documentation
        run: |
          mvn clean package -DskipTests=true
          bash src/main/bash/generate-documentation.bash
          mkdocs gh-deploy --force
